name: Container-tests by GitHub Action at Testing Farm

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    name: "Container PyTests: ${{ matrix.version }} - ${{ matrix.os_test }}"
    runs-on: ubuntu-latest
    concurrency:
      group: container-pytest-${{ github.event.issue.number }}-${{ matrix.version }}-${{ matrix.os_test }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os_test: [ "fedora", "rhel8", "rhel9", "c9s", "c10s", "rhel10" ]
        version: [ "core", "base" ]

    if: |
      github.event.issue.pull_request
      && (contains(github.event.comment.body, '[test-pytest]') || contains(github.event.comment.body, '[test-all]'))
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - uses: sclorg/tfaga-wrapper@main
        with:
          os_test: ${{ matrix.os_test }}
          version: ""
          working_dir: ${{ matrix.version }}
          test_case: "container-pytest"
          public_api_key: ${{ secrets.TF_PUBLIC_API_KEY }}
          private_api_key: ${{ secrets.TF_INTERNAL_API_KEY }}

